version: "2"

services:
  nginx:
    image: nginx-amplify
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./config/nginx/certs:/etc/nginx/certs:ro"
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      # - "./config/nginx/proxy/amplify.conf:/etc/nginx/conf.d/amplify.conf"
      - "./config/nginx/proxy/stub_status.conf:/etc/nginx/conf.d/stub_status.conf"
      - "./config/nginx/proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
      - "./config/logs:/var/log/nginx:rw"
    # networks:
    #   - proxy-tier
    network_mode: "bridge"
    environment:
      - API_KEY=18bc6b09f62c0f6cc6b3648d3b1c388b
      - AMPLIFY_IMAGENAME=nginx-amplify
  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./config/docker-gen/templates/nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/nginx/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  containers-manager:
    restart: always
    image: portainer/portainer 
    container_name: containers-manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=docker.bce.yongbuzhixi.com
      - LETSENCRYPT_HOST=docker.bce.yongbuzhixi.com
      - LETSENCRYPT_EMAIL=dale@yongbuzhixi.com
    # networks:
    #   - proxy-tier
    network_mode: "bridge"

# networks:
#   proxy-tier:
#     external:
#       name: nginx-proxy
